PRODUCTS = [
  "Benadryl Mucus Relief Double Action 100ml",
  "Ease A Cold Head Cold Fighter Tab X 24",
  "Chemists' Own Children's Paracetamol 1-5 Years 200ml",
  "Chemists' Own Children's Paracetamol 1-5 Years 100ml",
  "Demazin PE Cold & Flu Relief Tab X 24",
  "Demazin PE Cold & Flu Relief Tab X 48",
  "Robitussin Cough & Chest Congestion 100ml",
  "Nurofen Cold & Flu PE Tab X 24",
  "Nurofen Cold & Flu PE Tab X 48",
  "Bioglan Throat Clear Lozenges Honey and Lemon X 20",
  "Goanna Eucalyptus Oil 100ml",
  "Bisolvon Chesty Kids Liquid Strawberry 200ml ",
  "Bisolvon Dry Honey Lime Pastille X 20",
  "Chemists' Own Children's Cold & Allergy Mixture 100ml",
  "Ease A Cold Kids Cold & Flu Relief 120ml",
  "Benadryl Mucus Relief Double Action 200ml",
  "Children’s Paedamin Decongestant and Antihistamine 200ml",
  "Ease A Cold Cold & Congestion Liquid Cap X 30",
  "Maxiclear Sinus & Pain Relief Tab X 24",
  "Nature's Own Garlic + C, Horsereadish (Triple Strength) Tab X 100",
  "Cenovis Echinacea 5000mg Cap X 60",
  "Blooms Echinacea Formula Cap X 50",
  "Lifestream Natural Vitamin C Cap X 220",
  "Lifestream Natural Vitamin C Cap X 90",
  "Vitamax Vitamin C 500mg Tab X 400",
  "Blackmores Cold and Flu Day/Night Cap X 24",
  "Sambucol Cold & Flu Cap X 24",
  "Sambucol Cold & Flu 120ml",
  "Nature's Goodness Propolis 1000mg Tab X 60",
  "Blackmores Echinacea Forte 3000mg Tab X 150",
  "Nature's Own Garlic Oil Cap X 200",
  "Bioglan Airbourne Immunity Tab X 30",
  "Blackmores Super Strength Horseradish, Garlic + C Tab X 50",
  "Blackmores Super Strength Horseradish, Garlic + C Tab X 90",
  "Nature's Own Garlic Odourless 1000mg Tab X 50",
  "Ethical Nutrients Chesty Cough Relief 200ml",
  "Cenovis Echinacea, Garlic, Zinc and C Tab X 60",
  "Sambucol Throat Lozenges X 20",
  "Swisse Ultiboost High Strength C Tab X 60 ",
  "Ease A Cold Flu, Aches & Pain Day & Night Cap X 24",
  "Nature's Own Echinacea Complex Tab X 50",
  "Olive Leaf Australia Olive Skin Repair 200g"
]

PRODUCTS.each do |name|
  product = Product.find_by_name(name)
  Product.create(
    number: "#{rand(1000)}-#{rand(1000)}-#{rand(1000)}",
    name: name,
    width: rand(10)+1,
    height: rand(10)+1,
    depth: rand(10)+1,
    weight: rand(10)+1,
    stock_level: rand(10)+1,
  ) unless product
end